### ISSUE TITLE
ChatGPT can now accept subtitle file, is this translator still better?

### ISSUE THREAD

**Issue by romanr** [Cerlancism/chatgpt-subtitle-translator#11]
You can paste .srt file and tell to "treat subtitle as one continuous text. 
Isn't it better because it sees all text at once and then generates translation.

**Comment by Cerlancism** [comment]
What is the size of the .srt? The model still has context limits, I don't think it works completely for a long file like a 2 hour movie.

**Comment by romanr** [comment]
it's 600 parts. I can upload and translate by in pieces by 200.  Translate by telling it "treat text as continuous", nothing else required.

**Comment by Cerlancism** [comment]
Ok, so there are manual process involved to do the batching, which is one of the reason I made to tool to streamline this process.

Closing this issue since this tool is in fact designed to streamline this manual process and suits your use case.
