### ISSUE TITLE
Moderation warnings among the text

### ISSUE THREAD

**Issue by romanr** [Cerlancism/chatgpt-subtitle-translator#12]
Here's the output fragment:
```
445 "a bad man. You are
unworthy, you are stupid, you are" -> "[Flagged][Moderator] a bad man. You are
unworthy, you are stupid, you are -> harassment: 0.494 "
[CheckModeration] flagged [ { catergory: 'harassment', value: 0.9986397624015808 } ]
446 "ugly, you are failure, you"
```

Can moderation be turned off?

**Comment by chenyuAC** [comment]
Use 

`--no-use-moderator`

The purpose of the moderator is to check the likelihood if the model itself is unwilling to translate, and narrows from a large batch of 100 lines by default to the specific lines. If you turn the moderator off and the model is refusing to translate, it might tag is as `[Flagged][Model]`

**Comment by Cerlancism** [comment]
Add the command args 

`--no-use-moderator` 

The purpose of the moderator is to check the likelihood if the model itself is unwilling to translate, and narrows from a large batch of 100 lines by default to the specific lines. If you turn the moderator off and the model is refusing to translate, it might tag is as `[Flagged][Model]`
