### ISSUE TITLE
请问怎么设置代理服务器

### ISSUE THREAD

**Issue by bee2287448** [Cerlancism/chatgpt-subtitle-translator#14]
大佬你好，
我用windows 安装了nodejs，然后用命令行运行：
node cli\translator.mjs --plain-text "你好"
然后报错：
[Translator] System Instruction: Translate to English
[Error_CheckModeration] 2023-12-16T06:12:30.608Z Status undefined Error Connection error. undefined

我用clash进行代理，我在命令行窗口用
set http_proxy=127.0.0.1:7890
set https_proxy=127.0.0.1:7890
也不管用，请问怎么设置走代理。

**Comment by Cerlancism** [comment]
你好，

现在还没有直接支持走代理, 今晚我会试试看

**Comment by Cerlancism** [comment]
刚支持了 http_proxy 代理.

**Comment by bee2287448** [comment]
大佬， 我依然会报错：  你那句话 代理需要转换http--》https是什么意思呢？
E:\Program Files (x86)\chatgpt-subtitle-translator-1.4.0>node cli\translator.mjs --plain-text "你好"
[CLI HTTP PROXY] Using HTTP Proxy from ENV Detected http://127.0.0.1:7890
[Translator] System Instruction: Translate to English
[Error_CheckModeration] 2023-12-16T13:18:13.156Z Status 502 Error 502 status code (no body) undefined
[Error_CheckModeration] Retries 1 Delay 1000
[Error_CheckModeration] 2023-12-16T13:22:02.276Z Status 502 Error 502 status code (no body) undefined
[Error_CheckModeration] Retries 2 Delay 8000
[Error_CheckModeration] 2023-12-16T13:25:05.095Z Status undefined Error Connection error. undefined

**Comment by Cerlancism** [comment]
现在试一试 只在 `https_proxy` 但设置 `http://`
```
set https_proxy=http://127.0.0.1:7890
```
```
set https_proxy=http://127.0.0.1:7890

node cli\translator.mjs --plain-text "你好"
[CLI HTTP/HTTPS PROXY] Using HTTP/HTTP Proxy from ENV Detected {
  httpProxyConfig: undefined,
  httpsProxyConfig: 'http://127.0.0.1:7890'
}
[Translator] System Instruction: Translate to English
Hello
```
![image](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/28769707/1e8ed000-32b6-46cc-a486-9e0361bcea7b)

**Comment by bee2287448** [comment]
大佬，非常感谢，已经可以了。

**Comment by bee2287448** [comment]
大佬，非常感谢，已经可以了。
