### ISSUE TITLE
Web interface fails to translate

### ISSUE THREAD

**Issue by stulluk** [Cerlancism/chatgpt-subtitle-translator#15]
![image](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/5675664/c508e079-2f55-4713-8172-fb0f56f5aba6)

Here is my srt file: 
[outfile3.zip](https://github.com/Cerlancism/chatgpt-subtitle-translator/files/14118061/outfile3.zip)

Any suggestions? ( I also tried "use moderator")

**Comment by Cerlancism** [comment]
Try to open the browser inspector and take the screenshot of the error details from there.

Meanwhile I would fix the error display.

**Comment by Cerlancism** [comment]
Any updates? Are you on free tier? I think most likely it is rate limit issue.

**Comment by stulluk** [comment]
Yes, I am on free tier, do we need a paid plan to use this?

Here is updated error status:

![subtrans-error](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/5675664/bfa78d8e-2d0b-496b-b9df-3c9527381ae8)

![2024-02-03-10-42-20](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/5675664/edac77d5-52c6-42d1-b62e-6a5f9ccbae07)

![2024-02-03-10-42-39](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/5675664/42a7ea30-7067-4246-999d-d824c6ec07aa)

**Comment by Cerlancism** [comment]
I will implement rate limit options at the UI. You have to set it according to https://platform.openai.com/docs/guides/rate-limits/free-tier-rate-limits

However, this will only scoped to per request per minute (3 as of now), if you hit the day limit, which is 200, you have wait for the next day.

**Comment by stulluk** [comment]
Thank you for your kind and quick response. If I understand correctly, I have to wait for you to implement this "rate limit option selection in the UI".

Please ping me here when you updated it. I will retry again.

Also, it would be great to document this in the README for the end-users like me to avoid future issues.

**Comment by Cerlancism** [comment]
@stulluk Implemented rate limit controls at UI. You can set it to the lowest value `1` and turn off moderator. 

If you still hit quota error, you may have hit the RPD, which you have wait for next day.

**Comment by stulluk** [comment]
@Cerlancism 

![image](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/5675664/8e659346-c964-44bb-bcab-ffdad9cf1d1c)

Would it be possible for you to create a free account like me and try to translate above SRT file that I shared above ?

**Comment by Cerlancism** [comment]
I just took a closer look at your screenshot at

https://github.com/Cerlancism/chatgpt-subtitle-translator/issues/15#issuecomment-1925201128

Unfortunately your free credits already expired last year at Apr 01 2023. You have to use a paid plan now.

**Comment by stulluk** [comment]
@Cerlancism  thank you for clarifying. we can close the issue then.

**Comment by Cerlancism** [comment]
You are welcome! Thanks for trying out the application.
