### ISSUE TITLE
add custom base_Url in web

### ISSUE THREAD

**Issue by aliceric27** [Cerlancism/chatgpt-subtitle-translator#16]
你好，我目前嘗試開發web版本
因為我呼叫的API domain不是open ai 原地址 `https://api.openai.com`
我嘗試在web版新增`.env`檔案並且嘗試設定`OPENAI_BASE_URL`，不過好像沒有效果
想詢問如果我要在web版底下，嘗試使用自訂 api domain，應該如何修改呢?

Hello, I am currently trying to develop a web version. 
Since the API domain I am calling is not the original OpenAI address `https://api.openai.com`, I tried to add a `.env` file in the web version and set `OPENAI_BASE_URL`, but it doesn't seem to have any effect. I would like to ask how I should modify it if I want to try using a custom API domain in the web version.

**Comment by Cerlancism** [comment]
使用我的 web 版吗？<https://github.com/Cerlancism/chatgpt-subtitle-translator>
Web 版支持 env 是行的，但我不觉得合适， 并且 Next.js 需要加上 `NEXT_PUBLIC` 变成 `NEXT_PUBLIC_OPENAI_BASE_URL`
我在 `web` 加了一个 Base URL 框 

![image](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/28769707/2c1d5138-5efe-49e3-ab74-5dd6192cb74e)


我在 `cli` 版支持了 `env` `OPENAI_BASE_URL`

**Comment by aliceric27** [comment]
感謝更新這項功能，測試過後沒有問題

**Comment by aliceric27** [comment]
另外有個關於 NextUI 的問題想請教
我嘗試將 From language 和 To Language 兩個 `<input>` 修改為 `<select>`
並設定一些預設的語言方便操作和轉換，不過我的 Switch button 是有作用的，但  `<select>` 內的值不會改變
想詢問合適的 solution 或是哪邊我遺漏了，謝謝

[https://github.com/aliceric27/chatgpt-subtitle-translator/commit/b1c6760172afb5122441b51b456cd6f35e4dd63e](https://github.com/aliceric27/chatgpt-subtitle-translator/commit/b1c6760172afb5122441b51b456cd6f35e4dd63e)

**Comment by Cerlancism** [comment]
`Select` 使用 `selectedKeys` 和 `[]` 不是 `value`

```diff
@@ -258,7 +258,7 @@ export function TranslatorApplication()
                       label="From Language"
                       className="w-full md:w-6/12"
                       placeholder="Auto"
-                      value={fromLanguage}
+                      selectedKeys={fromLanguage ? [fromLanguage] : []}
                       items={LANGUAGE}
                       onChange={(e) => setFromLanguage(e.target.value)}
                     >
@@ -277,7 +277,7 @@ export function TranslatorApplication()
                       label="To Language"
                       className="w-full md:w-6/12"
                       placeholder="English"
-                      value={toLanguage}
+                      selectedKeys={[toLanguage]}
                       onChange={(e) => setToLanguage(e.target.value)}
                     >
                       {LANGUAGE.map((language) => (
```

**Comment by aliceric27** [comment]
非常感謝指點，沒有任何問題了

**Comment by Cerlancism** [comment]
不客气，感谢您对这个项目的兴趣。
