### ISSUE TITLE
Quota exceeded

### ISSUE THREAD

**Issue by mkatic007** [Cerlancism/chatgpt-subtitle-translator#17]
Hi, I have a GPT-4 paid subscription, but when using the web tool it gives me the error that the rate limit is exceeded even though I am using with only 3 RPM?

**Comment by Cerlancism** [comment]
Is your subscription specific to the API or just the https://chat.openai.com/
?

You need a separate API account billing at https://platform.openai.com/

**Comment by mkatic007** [comment]
Thank you! Works great!
