### ISSUE TITLE
Error_checkModeration Coordinated universal time connection error on Local

### ISSUE THREAD

**Issue by Milor123** [Cerlancism/chatgpt-subtitle-translator#18]
I am trying use my ollama mounted in local with LMstudio, but it not work

![image](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/14153649/7539c816-daad-4ac3-aa76-a6cde1d3e588)

what should i do? 
thank u very much !

**Comment by Cerlancism** [comment]
Try toggle off "Use Moderator"

![image](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/28769707/28703524-3e23-477a-9e7a-22eeb8322e03)

**Comment by Milor123** [comment]
thank you very much! it now works !
