### ISSUE TITLE
Error with JSON parsing

### ISSUE THREAD

**Issue by LiamK** [Cerlancism/chatgpt-subtitle-translator#2]
The subtitle translator is working pretty nicely, and the attention paid to backing off, and keeping numbers in sync is appreciated.  Unfortunately, it threw an exception, which resulted in no file being generated.  That's a bit unfortunate.  
I can split the file up in pieces and run them separately, so I think that will be a workaround.
I wonder, though, if it would be possible to update the output file incrementally.  That would help when recovering from errors such as this.  I'm happy to help debug this, however javascript is not my strongest language.

```
cli/translator.mjs --stream --temperature 0  --to Spanish --file ../translate/files/subtitle.srt 
...
node:internal/process/esm_loader:42
      internalBinding('errors').triggerUncaughtException(
                                ^
[Error_TranslationPrompt] Thu May 18 2023 17:50:19 GMT+0200 (Central European Summer Time) unknown error SyntaxError: Could not JSON parse stream message: Expected property name or '}' in JSON at position 151
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Comment by Cerlancism** [comment]
I am aware of this issue, will take a closer look. It seems to happen only in stream mode. 

For incremental saving, it is implemented, however it will only update if a batch is completed, it appears that your request fail during the generation of first batch, therefore no file output is saved
