### ISSUE TITLE
help me plz

### ISSUE THREAD

**Issue by saturndec** [Cerlancism/chatgpt-subtitle-translator#21]
I have filled in the API and url, and clicking translate works fine too. However, the translated content is exactly the same as the original text without any difference. Why is this? Please help me, thank you very much.

**Comment by saturndec** [comment]
I am using the provided web page.

**Comment by Cerlancism** [comment]
Screenshot? From which language to which language?

**Comment by saturndec** [comment]
![微信截图_20240308185653](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/153601736/65b6ae87-3c47-41df-aa2f-6a2079de426c)
I'm using the default text, translating from Japanese to English. Did I set something wrong? The other texts I uploaded also have this reaction. I feel like I've made a basic mistake😢

**Comment by Cerlancism** [comment]
I have not the custom base URL provider before, but what I see from its docs, it can be:


https://openkey.cloud/v1

**Comment by saturndec** [comment]
Many thanks! I switched to the official OpenAI API and it works normally now. I think there must have been a problem with the original API. Thank you for your answer!🤞🤞🤞

**Comment by Cerlancism** [comment]
Ok. Though I think the custom endpoint should also work if add the `v1`behind.

**Comment by saturndec** [comment]
I just tried again, it seems to be of no use, I'm not sure what the situation is. However, the problem has been resolved now, thank you.🙏
