### ISSUE TITLE
plans to implement GUI?

### ISSUE THREAD

**Issue by grandosegood** [Cerlancism/chatgpt-subtitle-translator#24]
hi there, do you plan to include a GUI for this wonderful tool? I'm currently using the web interface. Thanks.

**Comment by Cerlancism** [comment]
Hello, you mean desktop application or? Any specific reason? I think current web ui is sufficient the graphical user interface aspect.

**Comment by Cerlancism** [comment]
Closing as there isn't any follow ups. Native Desktop GUI is not deemed necessary as of now.
