### ISSUE TITLE
Please be compatible with llama.cpp

### ISSUE THREAD

**Issue by DDXDB** [Cerlancism/chatgpt-subtitle-translator#27]
When I use the OpenAI Base Url to link to llama.cpp
```
{"tid":"6312","timestamp":1713860426,"level":"INFO","function":"log_server_request","line":2875,"msg":"request","remote_addr":"127.0.0.1","remote_port":5213,"status":200,"method":"OPTIONS","path":"/v1/moderations","params":{}}
{"tid":"6312","timestamp":1713860426,"level":"INFO","function":"log_server_request","line":2875,"msg":"request","remote_addr":"127.0.0.1","remote_port":5213,"status":404,"method":"POST","path":"/v1/moderations","params":{}}
```
It seems to be moderations, but I confirm that my llama.cpp server is fine and other programs can communicate with it through the openAI API.

**Comment by Cerlancism** [comment]
You can disable moderator

CLI option
`--no-use-moderator`

**Comment by DDXDB** [comment]
> You can disable moderator
> 
> CLI option `--no-use-moderator`

Can it be implemented on the web? I prefer to use it on the web.

**Comment by Cerlancism** [comment]
It is already there

Toggle this one
![image](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/28769707/e9fd8610-9a39-49e5-b3c3-3b9659b085d7)
