### ISSUE TITLE
Where can I find your prompts?

### ISSUE THREAD

**Issue by ykk648** [Cerlancism/chatgpt-subtitle-translator#33]
Hi there, I‘m looking a perfect prompt to do srt translate mission, now I get some progress. Where can I find your prompts in this repo to learn about?

**Comment by Cerlancism** [comment]
The prompts are documented at:
https://github.com/Cerlancism/chatgpt-subtitle-translator?tab=readme-ov-file#how-it-works

The implementation can be found from:
https://github.com/Cerlancism/chatgpt-subtitle-translator/blob/ce2e1f90e4802f63ed211688e2203b69f92b8b28/src/translator.mjs#L93

**Comment by ykk648** [comment]
thanks, I’m using assistant api to achieve srt-translation in different languages, do more strict directions to the translate process, I cant opensource but it seems work better.
