### ISSUE TITLE
Experimental Structured Mode ZodError

### ISSUE THREAD

**Issue by andyhoeung** [Cerlancism/chatgpt-subtitle-translator#35]
Hey there, thank you for creating such a great project!

I wanted to try the experimental structured mode to translate from Japanese to English, but there seems to be a ZodError and would always fallback to base mode.

![image](https://github.com/user-attachments/assets/84bb052e-342b-4149-b408-4db20c9c9b3a)

I just enabled that mode and have temperature set to 0, besides having an input and a system instruction.

**Comment by Cerlancism** [comment]
Yes I am aware of this. This approach is using dynamically generated schema with the input values burnt into it. I was believing this way could force the LLM to output exact line quantity as the input, but as seen so far it actually cause more problems. I will continue to experiment various other approaches.

**Comment by Cerlancism** [comment]
This has become more reliable with the use of array structured format.
