### ISSUE TITLE
New Moderation API Integration

### ISSUE THREAD

**Issue by andyhoeung** [Cerlancism/chatgpt-subtitle-translator#38]
Will you be implementing the new moderation tool from OpenAI? I'm guessing since it's supposedly more accurate, it should decrease flagging which should improve token usage.

**Comment by Cerlancism** [comment]
Completed in 2c422adfcd824f5ee6966b0973466b7aaa83c99f and b86689a3a7eedb88ddfc6a6ddd8604953d202f82
