### ISSUE TITLE
[feature] Silent mode?

### ISSUE THREAD

**Issue by jaum20** [Cerlancism/chatgpt-subtitle-translator#43]
Thanks for the script!

Any way to make it run silent (no print text to the console terminal)?

**Comment by Cerlancism** [comment]
Supported log levels

  - `--log-level [level]`
    Log level (choices: "trace", "debug", "info", "warn", "error", "silent")
  - `--silent`
    Same as `--log-level silent`
  - `--quiet`
    Same as `--log-level silent`
