### ISSUE TITLE
i cannot use it?

### ISSUE THREAD

**Issue by jackcore21** [Cerlancism/chatgpt-subtitle-translator#5]
As a beginner, please assist me with a video tutorial on how to use your files. I am eager to utilise your files but need the knowledge to achieve it. Can you provide me with a video or direct me to one that can teach me how to use your files?

**Comment by Cerlancism** [comment]
This is a Command Line (CLI) Application. It is not designed to used by beginners from scratch and unfortunately most tutorials to use CLI application or running Node JS are geared towards developers.

However, you could ask ChatGPT to guide you along, for example if you are on Windows:
https://chat.openai.com/share/95cdb242-52e0-41d5-8350-e9832877b41b

**Comment by jackcore21** [comment]
I appreciate your prompt response and would like to express my gratitude.
