### ISSUE TITLE
gpt-4 not working

### ISSUE THREAD

**Issue by OrelSBinoklem** [Cerlancism/chatgpt-subtitle-translator#6]
![image](https://github.com/Cerlancism/chatgpt-subtitle-translator/assets/5640787/0998b9fe-0180-4150-8116-98f329397f1f)

**Comment by Cerlancism** [comment]
Looks like you still not have access to it and have to wait longer.

See if can get gpt-4 working at:
https://platform.openai.com/playground?mode=chat&model=gpt-4

**Comment by Cerlancism** [comment]
Marking the as invalid and closing this as there is no follow up
